name: deploy

on:
  workflow_run:
    workflows:
      - tests
    types:
      - completed
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Check if LARAVEL_CLOUD_API_TOKEN is set
        run: |
          if [[ -z "${{ secrets.LARAVEL_CLOUD_API_TOKEN }}" ]]; then
            echo "LARAVEL_CLOUD_API_TOKEN secret is not set"
            exit 1
          fi

      - name: Trigger Deploy Hook
        run: |
          echo "Deploying to production..."
          curl --fail -X POST "${{ secrets.LARAVEL_CLOUD_API_TOKEN }}"
